-- Seed inclusion data (ramps, devices, student profiles) for production
-- This migration ensures inclusion data exists even if seeds didn't run in order

-- Ramps
INSERT INTO ramps (name, description, short_description, sort_order) VALUES
    ('Rampa Digital', 'Dispositivos tecnologicos que facilitan el acceso digital para estudiantes con diversas necesidades. Incluye tablets, perifericos adaptados y herramientas de accesibilidad que permiten interactuar con contenido digital de forma autonoma.', 'Tecnologia adaptativa para acceso digital', 1),
    ('Rampa Didactico-Pedagogica', 'Herramientas analogicas y de baja tecnologia disenadas para facilitar actividades de lectura, escritura y manipulacion en el aula. Permiten adaptar actividades cotidianas sin requerir electricidad ni configuracion compleja.', 'Herramientas analogicas para lectura, escritura y manipulacion', 2),
    ('Rampa de Autorregulacion Sensorial', 'Elementos que ayudan a estudiantes a regular su estado sensorial y emocional durante la jornada escolar. Reducen la sobrecarga sensorial y permiten liberar energia de forma controlada sin interrumpir la clase.', 'Regulacion sensorial y emocional en el aula', 3)
ON CONFLICT DO NOTHING;

-- Devices: Rampa Digital (ramp_id looked up dynamically)
INSERT INTO devices (ramp_id, name, description, qr_code, how_to_use, recommendations, rationale, classroom_benefit, needs_description, evaluation_criteria, quantity, sort_order, image_url)
SELECT r.id, d.name, d.description, d.qr_code, d.how_to_use, d.recommendations, d.rationale, d.classroom_benefit, d.needs_description, d.evaluation_criteria, d.quantity, d.sort_order, d.image_url
FROM (VALUES
    ('Rampa Digital', 'Tablet educativa (10")',
     'Una tablet pensada para acompanar el trabajo en el aula cuando no todos los estudiantes acceden de la misma manera a las propuestas. Permite ajustar el recurso sin modificar la actividad para todo el grupo.',
     'DEVICE-TAB-001',
     'Encende la tablet. Ajusta las opciones de accesibilidad segun el estudiante (tamano de texto, lector de pantalla, uso de voz). Abri la actividad o app antes de entregarla. Acompana el inicio y deja que el estudiante avance con mayor autonomia.',
     'Revisa la carga antes de la clase. Usa funda protectora. Activa un modo de uso escolar para evitar distracciones. Proba la configuracion antes de la actividad. Ajusta en funcion de como responde el estudiante.',
     'La tablet no cambia la propuesta, cambia el acceso. Funciona como un apoyo para que el estudiante pueda comprender la consigna, sostener la actividad y expresar lo que sabe, sin quedar afuera.',
     'Para que mas estudiantes puedan participar de la misma propuesta, aunque necesiten apoyos diferentes para leer, escribir, ver, escuchar o interactuar.',
     'Acompana especialmente a estudiantes que: necesitan apoyos para la lectura o escritura; se benefician de informacion visual o auditiva; requieren alternativas al trabajo manual; necesitan mas tiempo o mayor autonomia. La tablet permite incluir sin separar, ofreciendo distintos caminos para llegar al mismo aprendizaje.',
     'No se trata de evaluar el dispositivo, sino como ayuda al aprendizaje. Observar: si el estudiante accede mejor a la consigna; si puede sostener la actividad por mas tiempo; si aumenta su autonomia (menos pedidos de ayuda); si logra expresar lo que sabe de otra forma; si la herramienta reduce frustracion o barreras.',
     3, 1, '/devices/tablet.png'),
    ('Rampa Digital', 'Auriculares con microfono',
     'Auriculares que mejoran el aislamiento del ruido ambiental y permiten el acceso a contenido por comando de voz. Una herramienta para que el estudiante pueda escuchar consignas, textos o instrucciones sin interferencias del entorno.',
     'DEVICE-AUR-001',
     'Conecta los auriculares a la tablet o dispositivo. Regula el volumen a un nivel adecuado antes de entregarlo. Verifica que el estudiante escucha bien y se siente comodo. Combina su uso con actividades donde la escucha sea central (lecturas, consignas orales, videos).',
     'Limpia los auriculares entre usos. Tene adaptadores disponibles si la tablet usa otro conector. Proba el audio antes de la actividad. Ofrecelos sin senalar la necesidad: como una opcion disponible. Observa si el estudiante los usa voluntariamente o los rechaza.',
     'Los auriculares no aislan al estudiante del grupo; le permiten acceder mejor a la propuesta. Funcionan como un apoyo para reducir barreras auditivas o de atencion, sin cambiar la consigna ni separar al estudiante de la clase.',
     'Para que el estudiante pueda concentrarse en una actividad que requiere escuchar, sin que el ruido del aula lo distraiga. Tambien permite usar funciones de voz de la tablet sin molestar al resto del grupo.',
     'Acompana especialmente a estudiantes que: se distraen con el ruido ambiental; necesitan escuchar las consignas mas de una vez; se benefician de acceder al contenido por via auditiva; usan funciones de voz o lectura en voz alta en la tablet.',
     'Observar: si el estudiante logra mantener la atencion durante mas tiempo; si accede mejor a las consignas o al contenido; si reduce la necesidad de repetir instrucciones; si el estudiante lo elige voluntariamente como apoyo; si mejora su participacion en actividades con componente auditivo.',
     3, 2, '/devices/auricular.png'),
    ('Rampa Digital', 'Mouse trackball',
     'Un mouse que se controla con una esfera en lugar de mover todo el dispositivo sobre la mesa. Pensado para estudiantes que tienen dificultades con el control motor fino. Se puede complementar con dos contactores externos para activar clic derecho e izquierdo por separado.',
     'DEVICE-TRK-001',
     'Conecta el mouse a la tablet o computadora (USB o adaptador OTG). Ajusta la velocidad del cursor en la configuracion del dispositivo. Si el estudiante necesita contactores, conectalos a los puertos del mouse. Mostra brevemente como mover la esfera y hacer clic. Deja que el estudiante explore y se familiarice antes de la actividad.',
     'Fija el mouse a la mesa con cinta antideslizante si el estudiante tiene movimientos involuntarios. Proba la velocidad del cursor con el estudiante antes de la clase. Limpia la esfera periodicamente para que gire bien. Si usas contactores, verifica que el estudiante distinga clic izquierdo y derecho.',
     'El mouse trackball no simplifica la actividad, cambia la forma de acceder a ella. Permite que el estudiante interactue con el mismo contenido digital que sus companeros, usando un dispositivo adaptado a su movimiento.',
     'Para que un estudiante que no puede manejar un mouse convencional pueda navegar la tablet o computadora, realizar actividades digitales y participar de las mismas propuestas que el resto del grupo.',
     'Acompana especialmente a estudiantes que: tienen dificultades para mover un mouse convencional; presentan control motor reducido en manos o brazos; necesitan una alternativa de interaccion con la pantalla; se benefician de dispositivos que requieren menos precision en el movimiento.',
     'Observar: si el estudiante logra navegar y completar actividades digitales; si gana autonomia en el uso del dispositivo con el tiempo; si participa en las mismas propuestas que el grupo; si reduce la necesidad de asistencia de un adulto para interactuar con la pantalla.',
     1, 3, '/devices/mouse.jpg'),
    ('Rampa Digital', 'Teclado CLEVY',
     'Un teclado con teclas mas grandes y colores diferenciados por grupos (vocales, consonantes, numeros, funciones). Disenado para estudiantes con dificultades motoras o cognitivas que necesitan un teclado mas claro y facil de usar.',
     'DEVICE-CLV-001',
     'Conecta el teclado a la tablet o computadora (USB o adaptador OTG). Colocalo frente al estudiante en una posicion comoda. Si usas el acrilico protector, colocalo encima para que el estudiante pueda presionar teclas sin activar varias a la vez. Mostra brevemente la distribucion de colores si es la primera vez.',
     'Usa el acrilico protector si el estudiante presiona varias teclas a la vez. Proba que el dispositivo lo reconozca antes de la clase. Combinalo con un predictor de texto si esta disponible en la tablet. No fuerces su uso si el estudiante ya tiene otra forma de escritura que funciona.',
     'El teclado CLEVY no cambia lo que el estudiante tiene que hacer, cambia como lo hace. Los colores y el tamano funcionan como apoyos visuales que reducen la carga cognitiva y motora al escribir.',
     'Para que un estudiante que no puede usar un teclado convencional pueda escribir, buscar informacion o completar actividades digitales. Los colores y el tamano ayudan a localizar las teclas sin frustrarse.',
     'Acompana especialmente a estudiantes que: tienen dificultades motoras para presionar teclas pequenas; necesitan apoyo visual para ubicar letras y numeros; se benefician de una interfaz mas clara y con menos estimulos; estan aprendiendo a escribir con teclado.',
     'Observar: si el estudiante logra escribir con mayor fluidez; si reduce errores de tipeo o frustracion; si puede completar consignas de escritura de forma mas autonoma; si la diferenciacion por colores le ayuda a ubicar teclas mas rapido.',
     1, 4, '/devices/teclado.png'),
    ('Rampa Digital', 'Stickers de contraste para teclado',
     'Stickers con letras grandes y colores contrastantes que se pegan sobre las teclas de un teclado convencional. Transforman cualquier teclado en uno mas accesible para personas con dificultades visuales.',
     'DEVICE-STK-001',
     'Pega los stickers sobre las teclas del teclado de la computadora o notebook. Asegurate de que cada letra quede centrada y visible. Verifica que el estudiante pueda leer las letras a la distancia de uso. Si es necesario, combinalo con aumento de brillo en la pantalla.',
     'Pega los stickers con el teclado limpio y seco para mejor adherencia. Tene stickers de repuesto por si se despegan. Verifica el contraste bajo la luz del aula (no siempre es ideal). Consulta al estudiante si el tamano y color le resultan comodos.',
     'Los stickers no cambian el teclado ni la actividad. Cambian la visibilidad del recurso para que el estudiante pueda participar sin depender de otro que le diga que tecla presionar.',
     'Para que un estudiante que no distingue bien las letras del teclado pueda escribir sin ayuda, usando un teclado que ya tiene la escuela.',
     'Acompana especialmente a estudiantes que: tienen baja vision o dificultades para distinguir letras pequenas; necesitan mayor contraste visual para leer; usan teclado pero se frustran al no encontrar las teclas.',
     'Observar: si el estudiante ubica las teclas mas rapido; si reduce errores y frustracion al escribir; si puede escribir de forma mas autonoma; si elige usar el teclado con stickers voluntariamente.',
     20, 5, '/devices/stickers.png'),
    ('Rampa Digital', 'Pulsador boton USB',
     'Un boton grande que se conecta por USB y permite activar funciones de la computadora o tablet con una sola presion. Funciona como alternativa al teclado o al mouse para estudiantes con severas dificultades en el control motor.',
     'DEVICE-PUL-001',
     'Conecta el pulsador al puerto USB de la computadora o tablet (con adaptador OTG si es necesario). Configura que accion realiza el pulsador (clic, enter, espacio) desde el software del dispositivo. Ubicalo en una posicion accesible para el estudiante (mesa, soporte, bandeja de silla). Proba que funcione antes de la actividad.',
     'Asegurate de que el pulsador este bien fijado y no se mueva al presionarlo. Proba diferentes posiciones para encontrar la mas comoda para el estudiante. Combinalo con software de barrido si el estudiante necesita recorrer opciones. Tene en cuenta que el tiempo de respuesta puede ser mayor: ajusta la actividad si es necesario.',
     'El pulsador no reduce la propuesta ni la simplifica. Abre una via de acceso para estudiantes que de otro modo no podrian interactuar con el contenido digital. Permite participar de la misma actividad que el grupo, usando el movimiento que el estudiante si puede realizar.',
     'Para que un estudiante que no puede usar teclado ni mouse convencional pueda interactuar con el dispositivo digital: avanzar en una actividad, seleccionar opciones o confirmar respuestas.',
     'Acompana especialmente a estudiantes que: no pueden usar teclado ni mouse convencional; tienen movilidad muy reducida en manos o brazos; pueden realizar al menos un movimiento voluntario y controlado (presion); necesitan una forma simplificada de interactuar con la pantalla.',
     'Observar: si el estudiante logra interactuar con el dispositivo de forma intencional; si puede participar de actividades digitales que antes no podia; si gana autonomia en la interaccion con el tiempo; si se reduce la necesidad de que otro manipule el dispositivo por el estudiante.',
     1, 6, NULL),
    ('Rampa Digital', 'Soporte flexible celular/tablet',
     'Brazo articulado con pinza que se fija a la mesa y sostiene un celular o tablet en la posicion que el alumno necesite. Permite ajustar altura, angulo e inclinacion.',
     'DEVICE-SOP-001',
     'Fija la base a la mesa con la pinza. Coloca el dispositivo en el soporte. Ajusta posicion segun la necesidad del alumno. Verifica que quede firme.',
     'Asegura bien la base antes de colocar el dispositivo. Verifica estabilidad periodicamente.',
     'Libera las manos del alumno para interactuar con la pantalla tactil, y posiciona el dispositivo en el angulo optimo para su campo visual o rango de movimiento.',
     'Para que el estudiante pueda usar la tablet o celular sin necesidad de sostenerlo, liberando las manos para interactuar con la pantalla.',
     'Acompana especialmente a estudiantes que: tienen movilidad reducida en manos o brazos; necesitan el dispositivo en un angulo especifico por su campo visual; se benefician de tener las manos libres para interactuar con la pantalla tactil.',
     'Observar: si el estudiante interactua con mayor autonomia con el dispositivo; si la posicion del soporte le permite acceder mejor al contenido; si reduce la fatiga al no tener que sostener el dispositivo.',
     1, 7, NULL),
    ('Rampa Didactico-Pedagogica', 'Pen reader (lapiz lector)',
     'Un lapiz electronico que escanea texto impreso y lo lee en voz alta. Permite que el estudiante escuche lo que dice un libro, una guia o una prueba sin depender de otra persona que se lo lea.',
     'DEVICE-PEN-001',
     'Carga el pen reader antes de la clase. Encendelo y selecciona el idioma si es necesario. Mostra al estudiante como pasar el lapiz por encima de una linea de texto. Verifica que el audio se escuche bien (con o sin auriculares). Deja que el estudiante practique con un texto breve antes de la actividad.',
     'Funciona mejor con textos impresos en tipografia clara y tamano mediano o grande. Combinalo con auriculares si el aula es ruidosa. Proba con el texto real de la actividad antes de la clase. Si el pen reader no reconoce bien una fuente, proba fotocopiar el texto con letra mas grande.',
     'El pen reader no lee por el estudiante: le da acceso al texto. Permite que participe de la misma propuesta de lectura que el grupo, usando otro canal (auditivo) para comprender el contenido.',
     'Para que un estudiante con dificultades de lectura pueda acceder al mismo texto que sus companeros, de forma autonoma. Tambien puede usarse en evaluaciones para garantizar accesibilidad.',
     'Acompana especialmente a estudiantes que: tienen dificultades para decodificar texto escrito; necesitan escuchar el texto para comprenderlo; se benefician de la lectura en voz alta pero no siempre hay alguien disponible; requieren accesibilidad en situacion de evaluacion.',
     'Observar: si el estudiante accede al contenido del texto con mayor comprension; si puede responder consignas de lectura de forma mas autonoma; si reduce la necesidad de que un adulto le lea en voz alta; si lo usa con confianza y sin frustracion.',
     1, 1, '/devices/penreader.png'),
    ('Rampa Didactico-Pedagogica', 'Regla lupa',
     'Una regla con una franja central que funciona como lupa y permite ampliar una linea de texto a la vez. Destaca la linea que el estudiante esta leyendo y agranda las letras para facilitar la lectura.',
     'DEVICE-LUP-001',
     'Coloca la regla sobre el texto impreso, alineando la franja de aumento con la linea que el estudiante va a leer. El estudiante desliza la regla hacia abajo a medida que avanza. No requiere configuracion ni carga.',
     'Funciona mejor con textos impresos en papel claro. Combinala con buena iluminacion en el puesto del estudiante. Tene mas de una por si varios estudiantes la necesitan. Deja que el estudiante la use a su ritmo, sin apurarlo.',
     'La regla lupa no cambia el texto ni la consigna. Cambia la forma en que el estudiante ve el contenido, haciendo visible lo que de otro modo seria una barrera.',
     'Para que un estudiante con dificultades visuales o de lectura pueda seguir un texto linea por linea, sin perderse y con letras mas grandes.',
     'Acompana especialmente a estudiantes que: tienen baja vision; se pierden al leer textos con muchas lineas; necesitan ampliar el tamano de las letras; se benefician de un apoyo visual para seguir la lectura.',
     'Observar: si el estudiante lee con mayor fluidez y menos errores; si logra completar la lectura sin perderse; si aumenta su autonomia al leer textos impresos; si elige usar la regla voluntariamente.',
     2, 2, '/devices/regla.png'),
    ('Rampa Didactico-Pedagogica', 'Regla de lectura con ventana',
     'Una regla opaca con una ventana transparente que permite ver solo una linea de texto a la vez. Bloquea el resto de la pagina para que el estudiante se concentre en lo que esta leyendo, sin distracciones visuales.',
     'DEVICE-VEN-001',
     'Coloca la regla sobre el texto con la ventana alineada a la linea que el estudiante va a leer. El estudiante desliza la regla hacia abajo a medida que avanza. No requiere configuracion ni carga.',
     'Combinala con textos que tengan interlineado generoso. Si el estudiante tambien necesita ampliar, combinala con la regla lupa. No fuerces su uso: algunos estudiantes prefieren senalar con el dedo. Tene varias disponibles para que mas estudiantes las prueben.',
     'La regla con ventana no reduce el texto: lo organiza visualmente para que el estudiante pueda procesarlo mejor. Es un apoyo para la atencion y la lectura sostenida, no para simplificar el contenido.',
     'Para que un estudiante que se pierde al leer o se distrae con el resto de la pagina pueda enfocarse en una sola linea. Reduce la sobrecarga visual y facilita la lectura sostenida.',
     'Acompana especialmente a estudiantes que: se distraen con el texto completo de la pagina; pierden la linea al leer; tienen dificultades de atencion sostenida; se benefician de reducir la informacion visual simultanea.',
     'Observar: si el estudiante lee sin saltear lineas; si logra sostener la lectura por mas tiempo; si mejora la comprension del texto; si reduce la frustracion al leer textos largos.',
     2, 3, '/devices/regla2.png'),
    ('Rampa Didactico-Pedagogica', 'Finger focus (senalador de dedo)',
     'Un pequeno senalador que se coloca en el dedo y ayuda a seguir el texto linea por linea mientras se lee. Mejora la autonomia y la fluidez lectora en estudiantes que necesitan un apoyo para no perderse en el texto.',
     'DEVICE-FIN-001',
     'Coloca el finger focus en el dedo indice del estudiante. Mostra como deslizar el dedo debajo de cada linea mientras lee. Deja que el estudiante se acostumbre al ritmo. No requiere configuracion ni carga.',
     'Es mas efectivo en textos impresos que en pantalla. Funciona bien combinado con la regla lupa o la regla con ventana. Deja que el estudiante lo use el tiempo que necesite; con la practica puede dejar de necesitarlo. Presentalo como una herramienta, no como una obligacion.',
     'El finger focus convierte un gesto natural (senalar con el dedo) en una herramienta de apoyo. No cambia la consigna ni el texto: guia la mirada y organiza la lectura.',
     'Para que el estudiante pueda seguir la lectura con su propio dedo de manera guiada, sin perder el renglon. Es especialmente util en lecturas individuales o en voz alta.',
     'Acompana especialmente a estudiantes que: pierden el renglon al leer; tienen dificultades del aprendizaje vinculadas a la lectura; se benefician de un apoyo fisico para guiar la mirada; estan desarrollando fluidez lectora.',
     'Observar: si el estudiante pierde menos el renglon; si aumenta la fluidez y velocidad de lectura; si logra leer de forma mas autonoma; si lo usa voluntariamente como apoyo.',
     2, 4, '/devices/finger focus.png'),
    ('Rampa Didactico-Pedagogica', 'Tijeras adaptadas',
     'Tijeras con apertura automatica: se abren solas despues de cada corte. Disenadas para estudiantes con dificultades motoras o movilidad reducida en las manos, que no pueden abrir tijeras convencionales.',
     'DEVICE-TIJ-001',
     'Entrega las tijeras al estudiante y mostra como funcionan: solo necesita presionar para cortar. Verifica que las use con la mano dominante y en posicion comoda. Acompana los primeros cortes y luego deja que trabaje de forma autonoma.',
     'Verifica el filo antes de cada uso. Guarda las tijeras en un lugar accesible pero seguro. Si el estudiante tiene dificultades severas, sostene el papel mientras corta. No las presentes como "especiales": son otra opcion de tijera.',
     'Las tijeras adaptadas permiten que el estudiante haga lo mismo que sus companeros en actividades manuales. No cambian la propuesta: eliminan la barrera motora para participar.',
     'Para que un estudiante que no puede abrir y cerrar tijeras comunes pueda participar de actividades de recorte como el resto del grupo. Solo necesita hacer fuerza para cerrar.',
     'Acompana especialmente a estudiantes que: tienen dificultades motoras en las manos; no pueden hacer el movimiento de apertura de tijeras convencionales; se fatigan rapido al usar herramientas manuales; necesitan una alternativa para participar de actividades de recorte.',
     'Observar: si el estudiante logra recortar de forma mas autonoma; si participa de actividades manuales que antes evitaba; si reduce la frustracion o el cansancio al cortar; si mejora la calidad del recorte con la practica.',
     1, 5, NULL),
    ('Rampa Didactico-Pedagogica', 'Pinzas de escritura',
     'Adaptadores de goma o silicona que se colocan sobre el lapiz para favorecer una postura correcta de los dedos al escribir. Recomendadas para estudiantes con dificultades motoras o cognitivas (como dispraxia) que afectan la forma de sostener el lapiz.',
     'DEVICE-PIN-001',
     'Coloca la pinza sobre el lapiz o lapicera del estudiante. Verifica que los dedos queden bien posicionados en la guia. Deja que el estudiante escriba algunas palabras para acostumbrarse. No fuerces una posicion si causa incomodidad.',
     'Tene distintos modelos si es posible: no todas las pinzas sirven para todos. Deja que el estudiante elija cual le resulta mas comoda. No la impongas como obligatoria: es un apoyo, no una correccion. Combinala con papel pautado si el estudiante tambien tiene dificultades con el tamano de la letra.',
     'Las pinzas no cambian la consigna de escritura: cambian la forma de sostener la herramienta. Facilitan que el estudiante pueda enfocarse en el contenido de lo que escribe, no en como sostener el lapiz.',
     'Para que un estudiante que tiene dificultades para sostener el lapiz pueda escribir con menos esfuerzo y mayor control. Ayuda a que la escritura sea mas legible y menos agotadora.',
     'Acompana especialmente a estudiantes que: tienen dificultades para sostener el lapiz correctamente; se fatigan rapido al escribir; presentan escritura poco legible por problemas de agarre; necesitan un apoyo motor para escribir con mas control.',
     'Observar: si mejora la legibilidad de la escritura; si el estudiante escribe durante mas tiempo sin cansarse; si reduce la tension en la mano al escribir; si lo adopta como apoyo habitual.',
     3, 6, '/devices/pinza.png'),
    ('Rampa de Autorregulacion Sensorial', 'Elastico para silla',
     'Una banda elastica que se coloca en las patas delanteras de la silla. Permite al estudiante mover los pies o piernas de forma controlada mientras esta sentado, sin hacer ruido ni interrumpir la clase.',
     'DEVICE-ELA-001',
     'Engancha el elastico entre las dos patas delanteras de la silla, a la altura de los pies. El estudiante apoya los pies sobre el elastico y lo estira o presiona mientras trabaja. No requiere instrucciones complejas: el movimiento es intuitivo.',
     'Verifica que el elastico este bien sujeto y no se suelte. Reemplazalo cuando pierda elasticidad. Ofrecelo sin hacer senalamientos: como una opcion disponible. Observa si el estudiante lo usa de forma productiva o si le genera mas distraccion.',
     'El elastico reconoce que algunos estudiantes necesitan moverse para concentrarse. No es un premio ni un castigo: es una herramienta de autorregulacion que permite sostener la atencion sin salir del lugar.',
     'Para que un estudiante que necesita moverse pueda liberar energia de forma silenciosa y controlada, facilitando su concentracion sin interrumpir al grupo.',
     'Acompana especialmente a estudiantes que: necesitan moverse para concentrarse; se inquietan al estar sentados mucho tiempo; se benefician de estimulos propioceptivos en los pies; interrumpen la clase por necesidad de movimiento.',
     'Observar: si el estudiante logra permanecer sentado mas tiempo; si mejora la concentracion en la tarea; si se reducen las interrupciones vinculadas al movimiento; si el estudiante lo elige como recurso de autorregulacion.',
     1, 1, NULL),
    ('Rampa de Autorregulacion Sensorial', 'Patas de silla (almohadillas sensoriales)',
     'Almohadillas o bandas que se colocan en las patas de la silla y proporcionan un estimulo sensorial al contacto. Ayudan a mejorar la concentracion y reducir la inquietud a traves de la estimulacion sensorial controlada.',
     'DEVICE-SOP-002',
     'Coloca las almohadillas en las patas de la silla del estudiante. El estudiante recibe estimulacion sensorial al sentarse o al mover levemente la silla. No requiere instruccion: el efecto es automatico al sentarse.',
     'Verifica que queden bien fijadas y no se suelten. Combina con el elastico para silla si el estudiante necesita mas estimulo. Observa si generan el efecto esperado o si el estudiante no las nota.',
     'Las patas sensoriales actuan como un regulador ambiental: ayudan al cuerpo a calmarse para que la mente pueda enfocarse. No son un recurso visible ni senalado: funcionan de forma discreta.',
     'Para proporcionar un canal sensorial que ayude al estudiante a regular su nivel de activacion, favoreciendo la atencion y la permanencia en la tarea.',
     'Acompana especialmente a estudiantes que: necesitan estimulos sensoriales para regularse; tienen dificultades para mantener la atencion; se benefician de apoyos discretos e integrados al mobiliario.',
     'Observar: si el estudiante se muestra mas regulado y atento; si permanece mas tiempo en la tarea; si se reducen las conductas de inquietud.',
     4, 2, '/devices/patas.png'),
    ('Rampa de Autorregulacion Sensorial', 'Time Timer (temporizador visual)',
     'Un reloj visual que muestra el paso del tiempo con un disco de color que se va reduciendo. Permite que el estudiante vea cuanto tiempo queda para una actividad sin necesitar leer la hora ni depender del docente.',
     'DEVICE-TIM-001',
     'Gira el disco al tiempo deseado (por ejemplo, 15 minutos). Ubicalo donde el estudiante pueda verlo facilmente. Explica brevemente: "cuando el color desaparezca, se termina el tiempo". Puede usarse para toda la clase o para un estudiante en particular.',
     'Usalo con tiempos realistas para la actividad. Evita usarlo como presion: es una guia, no un cronometro de competencia. Combinalo con consignas claras sobre que hacer cuando termine el tiempo. Puede ser util para toda la clase, no solo para un estudiante.',
     'El Time Timer hace visible algo abstracto: el paso del tiempo. Ayuda a estudiantes que necesitan previsibilidad y estructura para sostener una actividad, sin depender de avisos verbales constantes del docente.',
     'Para reducir la ansiedad del estudiante al darle una referencia visual clara del tiempo disponible. Facilita la organizacion de tareas, evaluaciones o actividades con tiempo limitado.',
     'Acompana especialmente a estudiantes que: se angustian al no saber cuanto tiempo queda; tienen dificultades para organizar su trabajo en el tiempo; necesitan previsibilidad y estructura; se benefician de apoyos visuales para la regulacion.',
     'Observar: si el estudiante se muestra menos ansioso durante actividades con tiempo; si logra organizar su trabajo de forma mas autonoma; si pregunta menos "cuanto falta?"; si mejora su rendimiento en actividades con tiempo limitado.',
     1, 3, NULL),
    ('Rampa de Autorregulacion Sensorial', 'Pelota antiestres de gel',
     'Una pelota rellena de gel suave y flexible que se adapta a la presion de la mano. Se usa para la autorregulacion sensorial: apretar, soltar, manipular mientras se trabaja en otra tarea.',
     'DEVICE-PEL-001',
     'Entrega la pelota al estudiante al inicio de la actividad o cuando notes que la necesita. No es necesario dar instrucciones: el uso es intuitivo. Si se usa como herramienta habitual, dejala en el puesto del estudiante.',
     'Verifica que el material este en buen estado y no tenga fugas. Tene mas de una por si se rompe. Si el estudiante la lanza o juega en vez de usarla para regularse, conversa sobre su proposito. Ofrecela sin senalar: como un recurso del aula.',
     'La pelota antiestres no distrae: regula. Permite que el estudiante canalice la energia que necesita descargar para poder enfocarse en la tarea.',
     'Para que un estudiante que necesita canalizar la tension, el estres o la ansiedad pueda hacerlo de forma silenciosa y controlada, sin interrumpir la clase ni desconectarse de la actividad.',
     'Acompana especialmente a estudiantes que: necesitan canalizar ansiedad o estres durante la clase; se benefician de estimulos tactiles para concentrarse; tienen dificultades para mantener la calma en situaciones de demanda; necesitan un recurso discreto de autorregulacion.',
     'Observar: si el estudiante se muestra mas regulado emocionalmente; si puede sostener la atencion mientras la usa; si reduce conductas de ansiedad o inquietud; si la usa de forma intencional y productiva.',
     1, 4, NULL),
    ('Rampa de Autorregulacion Sensorial', 'Auriculares cancelacion de ruido',
     'Auriculares que reducen el ruido ambiental sin reproducir sonido. Disenados para disminuir la sobrecarga sensorial auditiva, permitiendo que el estudiante se concentre sin necesidad de aislarse del grupo.',
     'DEVICE-ANC-001',
     'Ofrece los auriculares al estudiante cuando notes que el ruido le afecta o antes de actividades que suelen ser ruidosas. El estudiante se los coloca como cualquier auricular. No necesitan carga ni conexion: son pasivos (cancelacion por aislamiento fisico).',
     'Limpia las almohadillas entre usos. Tene en cuenta que el estudiante escucha menos: asegurate de que pueda ver las consignas tambien. Ofrecelos como opcion, no como obligacion. Si el estudiante habla con ellos puestos, puede no regular bien su volumen de voz.',
     'Los auriculares de cancelacion no sacan al estudiante de la clase: le permiten estar mejor dentro de ella. Son un recurso de regulacion sensorial que facilita la participacion sin modificar la propuesta.',
     'Para que un estudiante que se ve afectado por el ruido del aula pueda permanecer en la clase y participar de la actividad con menos interferencia sensorial. No lo aislan: reducen el impacto del ruido.',
     'Acompana especialmente a estudiantes que: se sobreestimulan con el ruido ambiental; tienen hipersensibilidad auditiva; necesitan un entorno mas silencioso para concentrarse; se angustian en situaciones con mucho ruido (recreo, clase ruidosa, actos).',
     'Observar: si el estudiante se muestra mas regulado y atento con los auriculares; si logra permanecer en la actividad durante mas tiempo; si participa mas cuando el ruido esta atenuado; si los elige voluntariamente cuando lo necesita.',
     1, 5, '/devices/protector copa.png')
) AS d(ramp_name, name, description, qr_code, how_to_use, recommendations, rationale, classroom_benefit, needs_description, evaluation_criteria, quantity, sort_order, image_url)
JOIN ramps r ON r.name = d.ramp_name
WHERE NOT EXISTS (SELECT 1 FROM devices WHERE devices.qr_code = d.qr_code);

-- Student inclusion profiles
INSERT INTO student_inclusion_profiles (student_id, is_transitory, difficulties, free_description)
SELECT s.id, v.is_transitory, v.difficulties, v.free_description
FROM (VALUES
    (1, false, ARRAY['Dificultades en motricidad fina (manos y brazos)'], 'Dificultades en motricidad fina, debilidades musculares en la mano, retrasos madurativos. Tiene dificultad para sostener el lapiz con la postura correcta y se fatiga rapidamente en actividades de escritura prolongada.'),
    (2, false, ARRAY['Dificultades para acceder a tecnologia digital'], 'Dificultad para acceder a tecnologia digital. Necesita dispositivos adaptados para interactuar con pantallas y teclados. Caso indicado para uso de eye tracking o pulsadores.'),
    (3, true, ARRAY['Dificultades de atencion sostenida y regulacion emocional'], 'Dificultad para mantener la atencion sostenida y regular emociones durante la jornada escolar. Se beneficia de estrategias de autorregulacion sensorial y apoyos visuales para la gestion del tiempo.')
) AS v(student_id, is_transitory, difficulties, free_description)
JOIN students s ON s.id = v.student_id
WHERE NOT EXISTS (SELECT 1 FROM student_inclusion_profiles WHERE student_inclusion_profiles.student_id = v.student_id);
